# Project information
site_name: Environment Sensor Bluetooth
site_description: Environment Sensor Bluetooth firmware documentation.
site_author: hktkzyx
copyright:
  Copyright &copy; 2022 hktkzyx.
  Content on this site is licensed under CC BY 4.0.

# Repository
repo_name: hktkzyx/environment-sensor-bluetooth
repo_url: https://github.com/hktkzyx/environment-sensor-bluetooth

# Configuration
nav:
  - Home: README.md
theme:
  name: material
  language: en
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
plugins:
  - search
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hktkzyx
    - icon: material/email
      link: mailto:<hktkzyx@yeah.net>


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - md_in_html # Images with caption
  - meta
  - tables
  - toc:
      permalink: true
  # MathJax
  - pymdownx.arithmatex:
      generic: true
  # Code block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      user: hktkzyx
      repo: environment-sensor-bluetooth
  - pymdownx.snippets
  - pymdownx.superfences

# MathJax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
